version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - default
      - backend

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${SEQUELIZE_PASSWORD}
      MYSQL_DATABASE: ${SEQUELIZE_DATABASE}

    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3306:3306
volumes:  
    mysql:
    mysql_config:

networks:
    backend:
        name: ${DOCKER_NETWORK}